INSERT INTO TB_CUSTOMER_BANKING (CUSTOMER_NAME, PHONE, CUSTOMER_NUMBER, NATIONAL_CODE)
VALUES ('John Doe', '123-456-7890', 'CUST001', 'NC001');

INSERT INTO TB_CUSTOMER_BANKING (CUSTOMER_NAME, PHONE, CUSTOMER_NUMBER, NATIONAL_CODE)
VALUES ('Jane Smith', '234-567-8901', 'CUST002', 'NC002');

INSERT INTO TB_CUSTOMER_BANKING (CUSTOMER_NAME, PHONE, CUSTOMER_NUMBER, NATIONAL_CODE)
VALUES ('Alice Johnson', '345-678-9012', 'CUST003', 'NC003');

INSERT INTO TB_ACCOUNT_BANKING (ACCOUNT_NUMBER, ACCOUNT_DATE, ACCOUNT_TYPE, ACCOUNT_AMOUNT, ACTIVE_STATUS, CUSTOMER_ID)
VALUES ('ACC001', TO_DATE('2022-01-15', 'YYYY-MM-DD'), 1, 1000.00, 1, 1);

INSERT INTO TB_ACCOUNT_BANKING (ACCOUNT_NUMBER, ACCOUNT_DATE, ACCOUNT_TYPE, ACCOUNT_AMOUNT, ACTIVE_STATUS, CUSTOMER_ID)
VALUES ('ACC002', TO_DATE('2022-02-20', 'YYYY-MM-DD'), 2, 2500.50, 1, 2);

INSERT INTO TB_ACCOUNT_BANKING (ACCOUNT_NUMBER, ACCOUNT_DATE, ACCOUNT_TYPE, ACCOUNT_AMOUNT, ACTIVE_STATUS, CUSTOMER_ID)
VALUES ('ACC003', TO_DATE('2022-03-25', 'YYYY-MM-DD'), 3, 300.75, 1, 3);

INSERT INTO TB_TRANSACTION_BANKING (TRACKING_NO, DATE_TIME, TRANSACTION_TYPE, TO_ACCOUNT_ID, TRANSACTION_AMOUNT, ACCOUNT_ID)
VALUES ('TRX001', TO_DATE('2022-04-10', 'YYYY-MM-DD'), 1, NULL, 500.00, 1);

INSERT INTO TB_TRANSACTION_BANKING (TRACKING_NO, DATE_TIME, TRANSACTION_TYPE, TO_ACCOUNT_ID, TRANSACTION_AMOUNT, ACCOUNT_ID)
VALUES ('TRX002', TO_DATE('2022-05-15', 'YYYY-MM-DD'), 2, NULL, 100.25, 2);

INSERT INTO TB_TRANSACTION_BANKING (TRACKING_NO, DATE_TIME, TRANSACTION_TYPE, TO_ACCOUNT_ID, TRANSACTION_AMOUNT, ACCOUNT_ID)
VALUES ('TRX003', TO_DATE('2022-06-20', 'YYYY-MM-DD'), 3, 1, 200.00, 3);
