-- Creating TB_CUSTOMER_BANKING table
CREATE TABLE TB_CUSTOMER_BANKING (
                                     CUSTOMER_ID NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                     CUSTOMER_NAME VARCHAR2(255) NOT NULL,
                                     PHONE VARCHAR2(255) NOT NULL UNIQUE,
                                     CUSTOMER_NUMBER VARCHAR2(255) NOT NULL UNIQUE,
                                     NATIONAL_CODE VARCHAR2(255) NOT NULL UNIQUE
);

-- Creating TB_ACCOUNT_BANKING table
CREATE TABLE TB_ACCOUNT_BANKING (
                                    ACCOUNT_ID NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                    ACCOUNT_NUMBER VARCHAR2(255) NOT NULL,
                                    ACCOUNT_DATE DATE NOT NULL,
                                    ACCOUNT_TYPE NUMBER(10) NOT NULL,
                                    ACCOUNT_AMOUNT NUMBER(19, 2),
                                    ACTIVE_STATUS NUMBER(1) NOT NULL,
                                    CUSTOMER_ID NUMBER NOT NULL,
                                    CONSTRAINT FK_CUSTOMER_ACCOUNT FOREIGN KEY (CUSTOMER_ID) REFERENCES TB_CUSTOMER_BANKING(CUSTOMER_ID)
);

-- Creating TB_TRANSACTION_BANKING table
CREATE TABLE TB_TRANSACTION_BANKING (
                                        TRANSACTION_ID RAW(16) DEFAULT SYS_GUID() PRIMARY KEY,
                                        TRACKING_NO VARCHAR2(255) NOT NULL UNIQUE,
                                        DATE_TIME DATE,
                                        TRANSACTION_TYPE NUMBER(10) NOT NULL,
                                        TO_ACCOUNT_ID NUMBER,
                                        TRANSACTION_AMOUNT NUMBER(19, 2),
                                        ACCOUNT_ID NUMBER,
                                        CONSTRAINT FK_ACCOUNT_TRANSACTION FOREIGN KEY (ACCOUNT_ID) REFERENCES TB_ACCOUNT_BANKING(ACCOUNT_ID)
);
