-- Insert data into TB_CUSTOMER_BANKING
INSERT INTO TB_CUSTOMER_BANKING (CUSTOMER_NAME, PHONE, CUSTOMER_NUMBER, NATIONAL_CODE)
VALUES ('John Doe', '123-456-7890', 'CUST123', 'NC12345');
INSERT INTO TB_CUSTOMER_BANKING (CUSTOMER_NAME, PHONE, CUSTOMER_NUMBER, NATIONAL_CODE)
VALUES ('Jane Smith', '987-654-3210', 'CUST124', 'NC67890');

-- Insert data into TB_ACCOUNT_BANKING
INSERT INTO TB_ACCOUNT_BANKING (ACCOUNT_NUMBER, ACCOUNT_DATE, ACCOUNT_TYPE, ACCOUNT_AMOUNT, ACTIVE_STATUS, CUSTOMER_ID)
VALUES ('ACC001', TO_DATE('2023-01-01', 'YYYY-MM-DD'), 1, 1000.00, 1, 1);  -- Current account
INSERT INTO TB_ACCOUNT_BANKING (ACCOUNT_NUMBER, ACCOUNT_DATE, ACCOUNT_TYPE, ACCOUNT_AMOUNT, ACTIVE_STATUS, CUSTOMER_ID)
VALUES ('ACC002', TO_DATE('2023-01-15', 'YYYY-MM-DD'), 2, 5000.00, 1, 2);  -- Long term account
