-- Create TB_CUSTOMER_BANKING table
CREATE TABLE TB_CUSTOMER_BANKING (
                                     CUSTOMER_ID NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
                                     CUSTOMER_NAME VARCHAR2(255) NOT NULL,
                                     PHONE VARCHAR2(255) NOT NULL UNIQUE,
                                     CUSTOMER_NUMBER VARCHAR2(255) NOT NULL UNIQUE,
                                     NATIONAL_CODE VARCHAR2(255) NOT NULL UNIQUE
);

-- Create TB_ACCOUNT_BANKING table
CREATE TABLE TB_ACCOUNT_BANKING (
                                    ACCOUNT_ID NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
                                    ACCOUNT_NUMBER VARCHAR2(255) NOT NULL,
                                    ACCOUNT_DATE DATE NOT NULL,
                                    ACCOUNT_TYPE NUMBER NOT NULL,  -- EnumType.ORDINAL stored as NUMBER
                                    ACCOUNT_AMOUNT NUMBER(19, 2),
                                    ACTIVE_STATUS NUMBER(1) NOT NULL,
                                    CUSTOMER_ID NUMBER NOT NULL,
                                    CONSTRAINT FK_ACCOUNT_CUSTOMER FOREIGN KEY (CUSTOMER_ID) REFERENCES TB_CUSTOMER_BANKING(CUSTOMER_ID)
);

-- Create TB_TRANSACTION_BANKING table
CREATE TABLE TB_TRANSACTION_BANKING (
                                        TRANSACTION_ID RAW(16) DEFAULT SYS_GUID() PRIMARY KEY,
                                        TRACKING_NO VARCHAR2(255) NOT NULL UNIQUE,
                                        DATE_TIME DATE,
                                        TRANSACTION_TYPE NUMBER NOT NULL,  -- EnumType.ORDINAL stored as NUMBER
                                        TO_ACCOUNT_ID NUMBER,
                                        TRANSACTION_AMOUNT NUMBER(19, 2),
                                        TRANSACTION_STATUS NUMBER,  -- EnumType.ORDINAL stored as NUMBER
                                        DELETE_STATUS NUMBER(1),
                                        ACCOUNT_ID NUMBER,
                                        CONSTRAINT FK_TRANSACTION_ACCOUNT FOREIGN KEY (ACCOUNT_ID) REFERENCES TB_ACCOUNT_BANKING(ACCOUNT_ID)
);


-- Create sequence for tracking number
CREATE SEQUENCE tracking_no_seq
    START WITH 1
    INCREMENT BY 1
    CACHE 20;

